# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Eruditionis Itinere
tagline:             'tukangkod.github.io'
description:         'A journey of learning and growing'
url:                 https://tukangkod.github.io
baseurl:             ''
paginate:            5
google_analytics:	 UA-110057158-1

# About/contact
author:
  name:              Fahmi Adam
  url:               https://twitter.com/tukangkod
  email:             mohammad@fahmi.my

# Custom vars
version:             1.0.0
