# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               TukangKod.github.io
tagline:             'Eruditionis Itinere'
description:         'Bertukang dengan kod'
url:                 http://tukangkod.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Fahmi Adam
  url:               https://twitter.com/tukangkod
  email:             mohammad@fahmi.my

# Custom vars
version:             1.0.0
